import { ref } from 'vue'

const list = ref([
  {
    timeDiff: null,
    operator: {
      fio: 'Мокринская Ирина Михайловна',
      shortFio: 'Мокринская И. М.',
      id: 29,
    },
    sro: {
      id: 'igs',
      shortName: 'ИГС',
    },
    memberDoStatus: {
      id: 2,
      title: 'Партнер',
    },
    id: 522,
    shortname: '«ГазСтройПроект»',
    inn: '1649022016',
    controlComment: 'ds',
    controlDate: '2024-11-18 00:00:00',
  },
  {
    timeDiff: null,
    operator: {
      fio: 'Кузьмичёва Елизавета Дмитриевна',
      shortFio: 'Кузьмичёва Е. Д.',
      id: 26,
    },
    sro: {
      id: 'igs',
      shortName: 'ИГС',
    },
    memberDoStatus: {
      id: 2,
      title: 'Партнер',
    },
    id: 401,
    shortname: 'ИТЦ «Самараинжиниринг»',
    inn: '6317037917',
    controlComment: 'dsa',
    controlDate: '2024-11-19 00:00:00',
  },
  {
    timeDiff: '9',
    operator: {
      fio: 'Кузьмичёва Елизавета Дмитриевна',
      shortFio: 'Кузьмичёва Е. Д.',
      id: 26,
    },
    sro: {
      id: 'igs',
      shortName: 'ИГС',
    },
    memberDoStatus: {
      id: 2,
      title: 'Партнер',
    },
    id: 110,
    shortname: '«ГарантКонтракт»',
    inn: '4101159669',
    controlComment: 'Test',
    controlDate: '2024-11-14 00:00:00',
  },
  {
    timeDiff: '3',
    operator: {
      fio: 'Соколов Алексей Петрович',
      shortFio: 'Соколов А. П.',
      id: 31,
    },
    sro: {
      id: 'msp',
      shortName: 'МСП',
    },
    memberDoStatus: {
      id: 1,
      title: 'Член',
    },
    id: 233,
    shortname: 'ООО «СтройСервис»',
    inn: '7712345678',
    controlComment: 'Проверка документов',
    controlDate: '2024-11-20 00:00:00',
  },
  {
    timeDiff: '7',
    operator: {
      fio: 'Иванова Светлана Николаевна',
      shortFio: 'Иванова С. Н.',
      id: 35,
    },
    sro: {
      id: 'igs',
      shortName: 'ИГС',
    },
    memberDoStatus: {
      id: 3,
      title: 'Ассоциированный член',
    },
    id: 178,
    shortname: 'АО «ТехноСтрой»',
    inn: '5012367891',
    controlComment: 'Плановая проверка',
    controlDate: '2024-11-15 00:00:00',
  },
  {
    timeDiff: null,
    operator: {
      fio: 'Мокринская Ирина Михайловна',
      shortFio: 'Мокринская И. М.',
      id: 29,
    },
    sro: {
      id: 'pts',
      shortName: 'ПТС',
    },
    memberDoStatus: {
      id: 2,
      title: 'Партнер',
    },
    id: 455,
    shortname: '«ПромИнжиниринг»',
    inn: '3642987651',
    controlComment: 'Внеплановая проверка',
    controlDate: '2024-11-22 00:00:00',
  },
  {
    timeDiff: '5',
    operator: {
      fio: 'Петров Дмитрий Сергеевич',
      shortFio: 'Петров Д. С.',
      id: 42,
    },
    sro: {
      id: 'msp',
      shortName: 'МСП',
    },
    memberDoStatus: {
      id: 1,
      title: 'Член',
    },
    id: 301,
    shortname: 'ЗАО «МостДорСтрой»',
    inn: '8943216578',
    controlComment: 'Ежегодный аудит',
    controlDate: '2024-11-17 00:00:00',
  },
  {
    timeDiff: '12',
    operator: {
      fio: 'Кузьмичёва Елизавета Дмитриевна',
      shortFio: 'Кузьмичёва Е. Д.',
      id: 26,
    },
    sro: {
      id: 'igs',
      shortName: 'ИГС',
    },
    memberDoStatus: {
      id: 2,
      title: 'Партнер',
    },
    id: 189,
    shortname: 'ООО «СпецСтройКонтракт»',
    inn: '2267534991',
    controlComment: 'Согласованные действия',
    controlDate: '2024-11-10 00:00:00',
  },
  {
    timeDiff: '2',
    operator: {
      fio: 'Соколов Алексей Петрович',
      shortFio: 'Соколов А. П.',
      id: 31,
    },
    sro: {
      id: 'pts',
      shortName: 'ПТС',
    },
    memberDoStatus: {
      id: 3,
      title: 'Ассоциированный член',
    },
    id: 277,
    shortname: '«ГражданПроект»',
    inn: '1123457689',
    controlComment: 'Дополнительная инспекция',
    controlDate: '2024-11-21 00:00:00',
  },
  {
    timeDiff: null,
    operator: {
      fio: 'Иванова Светлана Николаевна',
      shortFio: 'Иванова С. Н.',
      id: 35,
    },
    sro: {
      id: 'msp',
      shortName: 'МСП',
    },
    memberDoStatus: {
      id: 1,
      title: 'Член',
    },
    id: 567,
    shortname: 'ПАО «СтройМонтаж»',
    inn: '5487612309',
    controlComment: 'Проверка сертификатов',
    controlDate: '2024-11-25 00:00:00',
  },
  {
    timeDiff: '8',
    operator: {
      fio: 'Мокринская Ирина Михайловна',
      shortFio: 'Мокринская И. М.',
      id: 29,
    },
    sro: {
      id: 'igs',
      shortName: 'ИГС',
    },
    memberDoStatus: {
      id: 2,
      title: 'Партнер',
    },
    id: 415,
    shortname: 'ООО «ВолгаСтрой»',
    inn: '6453127865',
    controlComment: 'Мониторинг',
    controlDate: '2024-11-16 00:00:00',
  },
  {
    timeDiff: '1',
    operator: {
      fio: 'Петров Дмитрий Сергеевич',
      shortFio: 'Петров Д. С.',
      id: 42,
    },
    sro: {
      id: 'pts',
      shortName: 'ПТС',
    },
    memberDoStatus: {
      id: 3,
      title: 'Ассоциированный член',
    },
    id: 390,
    shortname: '«ЭнергоСтрой»',
    inn: '9812734561',
    controlComment: 'Квартальный отчет',
    controlDate: '2024-11-22 00:00:00',
  },
  {
    timeDiff: '15',
    operator: {
      fio: 'Кузьмичёва Елизавета Дмитриевна',
      shortFio: 'Кузьмичёва Е. Д.',
      id: 26,
    },
    sro: {
      id: 'msp',
      shortName: 'МСП',
    },
    memberDoStatus: {
      id: 2,
      title: 'Партнер',
    },
    id: 275,
    shortname: 'АО «ПромСтройДизайн»',
    inn: '3251648790',
    controlComment: 'Итоговая проверка',
    controlDate: '2024-11-07 00:00:00',
  },
  {
    timeDiff: null,
    operator: {
      fio: 'Соколов Алексей Петрович',
      shortFio: 'Соколов А. П.',
      id: 31,
    },
    sro: {
      id: 'igs',
      shortName: 'ИГС',
    },
    memberDoStatus: {
      id: 1,
      title: 'Член',
    },
    id: 193,
    shortname: 'ООО «ТрансСтройПроект»',
    inn: '4578123690',
    controlComment: 'Аудит безопасности',
    controlDate: '2024-11-23 00:00:00',
  },
  {
    timeDiff: '6',
    operator: {
      fio: 'Иванова Светлана Николаевна',
      shortFio: 'Иванова С. Н.',
      id: 35,
    },
    sro: {
      id: 'pts',
      shortName: 'ПТС',
    },
    memberDoStatus: {
      id: 2,
      title: 'Партнер',
    },
    id: 345,
    shortname: '«ДорСтройИнвест»',
    inn: '7896543212',
    controlComment: 'Проверка лицензии',
    controlDate: '2024-11-18 00:00:00',
  },
  {
    timeDiff: '4',
    operator: {
      fio: 'Мокринская Ирина Михайловна',
      shortFio: 'Мокринская И. М.',
      id: 29,
    },
    sro: {
      id: 'msp',
      shortName: 'МСП',
    },
    memberDoStatus: {
      id: 3,
      title: 'Ассоциированный член',
    },
    id: 427,
    shortname: 'ЗАО «СвязьСтройКомплекс»',
    inn: '2345678901',
    controlComment: 'Ревизия документации',
    controlDate: '2024-11-19 00:00:00',
  },
  {
    timeDiff: null,
    operator: {
      fio: 'Петров Дмитрий Сергеевич',
      shortFio: 'Петров Д. С.',
      id: 42,
    },
    sro: {
      id: 'igs',
      shortName: 'ИГС',
    },
    memberDoStatus: {
      id: 1,
      title: 'Член',
    },
    id: 532,
    shortname: 'ПАО «СтройКомплект»',
    inn: '6123789045',
    controlComment: 'Ежемесячная проверка',
    controlDate: '2024-11-24 00:00:00',
  },
  {
    timeDiff: '10',
    operator: {
      fio: 'Кузьмичёва Елизавета Дмитриевна',
      shortFio: 'Кузьмичёва Е. Д.',
      id: 26,
    },
    sro: {
      id: 'pts',
      shortName: 'ПТС',
    },
    memberDoStatus: {
      id: 2,
      title: 'Партнер',
    },
    id: 198,
    shortname: 'ООО «АрхПроектСтрой»',
    inn: '8901234567',
    controlComment: 'Проверка разрешений',
    controlDate: '2024-11-13 00:00:00',
  },
  {
    timeDiff: '5',
    operator: {
      fio: 'Соколов Алексей Петрович',
      shortFio: 'Соколов А. П.',
      id: 31,
    },
    sro: {
      id: 'msp',
      shortName: 'МСП',
    },
    memberDoStatus: {
      id: 3,
      title: 'Ассоциированный член',
    },
    id: 312,
    shortname: '«ИнжСтройКомплекс»',
    inn: '3456789012',
    controlComment: 'Регулярный осмотр',
    controlDate: '2024-11-18 00:00:00',
  },
  {
    timeDiff: null,
    operator: {
      fio: 'Иванова Светлана Николаевна',
      shortFio: 'Иванова С. Н.',
      id: 35,
    },
    sro: {
      id: 'igs',
      shortName: 'ИГС',
    },
    memberDoStatus: {
      id: 1,
      title: 'Член',
    },
    id: 489,
    shortname: 'АО «СтройКонструкция»',
    inn: '7890123456',
    controlComment: 'Проверка соответствия',
    controlDate: '2024-11-26 00:00:00',
  },
  {
    timeDiff: '7',
    operator: {
      fio: 'Мокринская Ирина Михайловна',
      shortFio: 'Мокринская И. М.',
      id: 29,
    },
    sro: {
      id: 'pts',
      shortName: 'ПТС',
    },
    memberDoStatus: {
      id: 2,
      title: 'Партнер',
    },
    id: 236,
    shortname: 'ООО «ТехноСтройПроект»',
    inn: '9012345678',
    controlComment: 'Анализ документов',
    controlDate: '2024-11-17 00:00:00',
  },
  {
    timeDiff: '2',
    operator: {
      fio: 'Петров Дмитрий Сергеевич',
      shortFio: 'Петров Д. С.',
      id: 42,
    },
    sro: {
      id: 'msp',
      shortName: 'МСП',
    },
    memberDoStatus: {
      id: 3,
      title: 'Ассоциированный член',
    },
    id: 417,
    shortname: '«МонтажСпецСтрой»',
    inn: '4567890123',
    controlComment: 'Дополнительная проверка',
    controlDate: '2024-11-21 00:00:00',
  },
  {
    timeDiff: null,
    operator: {
      fio: 'Кузьмичёва Елизавета Дмитриевна',
      shortFio: 'Кузьмичёва Е. Д.',
      id: 26,
    },
    sro: {
      id: 'igs',
      shortName: 'ИГС',
    },
    memberDoStatus: {
      id: 1,
      title: 'Член',
    },
    id: 562,
    shortname: 'ЗАО «ИнвестСтрой»',
    inn: '5678901234',
    controlComment: 'Проверка отчетности',
    controlDate: '2024-11-27 00:00:00',
  },
  {
    timeDiff: '14',
    operator: {
      fio: 'Соколов Алексей Петрович',
      shortFio: 'Соколов А. П.',
      id: 31,
    },
    sro: {
      id: 'pts',
      shortName: 'ПТС',
    },
    memberDoStatus: {
      id: 2,
      title: 'Партнер',
    },
    id: 155,
    shortname: 'ООО «СпецСтройМонтаж»',
    inn: '6789012345',
    controlComment: 'Регламентная проверка',
    controlDate: '2024-11-08 00:00:00',
  },
  {
    timeDiff: '3',
    operator: {
      fio: 'Иванова Светлана Николаевна',
      shortFio: 'Иванова С. Н.',
      id: 35,
    },
    sro: {
      id: 'msp',
      shortName: 'МСП',
    },
    memberDoStatus: {
      id: 3,
      title: 'Ассоциированный член',
    },
    id: 324,
    shortname: '«РемСтройСервис»',
    inn: '7890123456',
    controlComment: 'Штатная проверка',
    controlDate: '2024-11-20 00:00:00',
  },
  {
    timeDiff: null,
    operator: {
      fio: 'Мокринская Ирина Михайловна',
      shortFio: 'Мокринская И. М.',
      id: 29,
    },
    sro: {
      id: 'igs',
      shortName: 'ИГС',
    },
    memberDoStatus: {
      id: 1,
      title: 'Член',
    },
    id: 478,
    shortname: 'ПАО «СтройИнжиниринг»',
    inn: '8901234567',
    controlComment: 'Итоговая инспекция',
    controlDate: '2024-11-28 00:00:00',
  },
  {
    timeDiff: '6',
    operator: {
      fio: 'Петров Дмитрий Сергеевич',
      shortFio: 'Петров Д. С.',
      id: 42,
    },
    sro: {
      id: 'pts',
      shortName: 'ПТС',
    },
    memberDoStatus: {
      id: 2,
      title: 'Партнер',
    },
    id: 221,
    shortname: 'ООО «ПроектСтройГрупп»',
    inn: '9012345678',
    controlComment: 'Плановый осмотр',
    controlDate: '2024-11-18 00:00:00',
  },
  {
    timeDiff: '11',
    operator: {
      fio: 'Кузьмичёва Елизавета Дмитриевна',
      shortFio: 'Кузьмичёва Е. Д.',
      id: 26,
    },
    sro: {
      id: 'msp',
      shortName: 'МСП',
    },
    memberDoStatus: {
      id: 3,
      title: 'Ассоциированный член',
    },
    id: 166,
    shortname: '«СтройКонтракт»',
    inn: '0123456789',
    controlComment: 'Проверка статуса',
    controlDate: '2024-11-12 00:00:00',
  },
  {
    timeDiff: null,
    operator: {
      fio: 'Соколов Алексей Петрович',
      shortFio: 'Соколов А. П.',
      id: 31,
    },
    sro: {
      id: 'igs',
      shortName: 'ИГС',
    },
    memberDoStatus: {
      id: 1,
      title: 'Член',
    },
    id: 545,
    shortname: 'АО «СтройКомплекс»',
    inn: '1234567890',
    controlComment: 'Проверка сертификации',
    controlDate: '2024-11-29 00:00:00',
  },
  {
    timeDiff: '4',
    operator: {
      fio: 'Иванова Светлана Николаевна',
      shortFio: 'Иванова С. Н.',
      id: 35,
    },
    sro: {
      id: 'pts',
      shortName: 'ПТС',
    },
    memberDoStatus: {
      id: 2,
      title: 'Партнер',
    },
    id: 289,
    shortname: 'ООО «ГорСтройПроект»',
    inn: '2345678901',
    controlComment: 'Оценка соответствия',
    controlDate: '2024-11-19 00:00:00',
  },
  {
    timeDiff: '8',
    operator: {
      fio: 'Мокринская Ирина Михайловна',
      shortFio: 'Мокринская И. М.',
      id: 29,
    },
    sro: {
      id: 'msp',
      shortName: 'МСП',
    },
    memberDoStatus: {
      id: 3,
      title: 'Ассоциированный член',
    },
    id: 212,
    shortname: '«ПромСтройИнвест»',
    inn: '3456789012',
    controlComment: 'Внутренний аудит',
    controlDate: '2024-11-16 00:00:00',
  },
  {
    timeDiff: null,
    operator: {
      fio: 'Петров Дмитрий Сергеевич',
      shortFio: 'Петров Д. С.',
      id: 42,
    },
    sro: {
      id: 'igs',
      shortName: 'ИГС',
    },
    memberDoStatus: {
      id: 1,
      title: 'Член',
    },
    id: 498,
    shortname: 'ЗАО «МостСтройСервис»',
    inn: '4567890123',
    controlComment: 'Техническая проверка',
    controlDate: '2024-11-30 00:00:00',
  },
  {
    timeDiff: '13',
    operator: {
      fio: 'Кузьмичёва Елизавета Дмитриевна',
      shortFio: 'Кузьмичёва Е. Д.',
      id: 26,
    },
    sro: {
      id: 'pts',
      shortName: 'ПТС',
    },
    memberDoStatus: {
      id: 2,
      title: 'Партнер',
    },
    id: 145,
    shortname: 'ООО «СтройДорПроект»',
    inn: '5678901234',
    controlComment: 'Проверка лицензий',
    controlDate: '2024-11-09 00:00:00',
  },
  {
    timeDiff: '2',
    operator: {
      fio: 'Соколов Алексей Петрович',
      shortFio: 'Соколов А. П.',
      id: 31,
    },
    sro: {
      id: 'msp',
      shortName: 'МСП',
    },
    memberDoStatus: {
      id: 3,
      title: 'Ассоциированный член',
    },
    id: 356,
    shortname: '«ТехСтройМонтаж»',
    inn: '6789012345',
    controlComment: 'Проверка сметы',
    controlDate: '2024-11-21 00:00:00',
  },
  {
    timeDiff: null,
    operator: {
      fio: 'Иванова Светлана Николаевна',
      shortFio: 'Иванова С. Н.',
      id: 35,
    },
    sro: {
      id: 'igs',
      shortName: 'ИГС',
    },
    memberDoStatus: {
      id: 1,
      title: 'Член',
    },
    id: 511,
    shortname: 'ПАО «СтройСервисГрупп»',
    inn: '7890123456',
    controlComment: 'Финальная инспекция',
    controlDate: '2024-12-01 00:00:00',
  },
  {
    timeDiff: '5',
    operator: {
      fio: 'Мокринская Ирина Михайловна',
      shortFio: 'Мокринская И. М.',
      id: 29,
    },
    sro: {
      id: 'pts',
      shortName: 'ПТС',
    },
    memberDoStatus: {
      id: 2,
      title: 'Партнер',
    },
    id: 268,
    shortname: 'ООО «ИнжСтройПроект»',
    inn: '8901234567',
    controlComment: 'Сверка документов',
    controlDate: '2024-11-19 00:00:00',
  },
  {
    timeDiff: '16',
    operator: {
      fio: 'Кузьмичёва Елизавета Дмитриевна',
      shortFio: 'Кузьмичёва Е. Д.',
      id: 26,
    },
    sro: {
      id: 'msp',
      shortName: 'МСП',
    },
    memberDoStatus: {
      id: 3,
      title: 'Ассоциированный член',
    },
    id: 134,
    shortname: '«АльфаСтройИнвест»',
    inn: '9012345678',
    controlComment: 'Проект контроля',
    controlDate: '2024-11-06 00:00:00',
  },
  {
    timeDiff: null,
    operator: {
      fio: 'Соколов Алексей Петрович',
      shortFio: 'Соколов А. П.',
      id: 31,
    },
    sro: {
      id: 'igs',
      shortName: 'ИГС',
    },
    memberDoStatus: {
      id: 1,
      title: 'Член',
    },
    id: 585,
    shortname: 'АО «СпецСтройТрест»',
    inn: '0123456789',
    controlComment: 'Годовая инспекция',
    controlDate: '2024-12-02 00:00:00',
  },
])

export { list }
